server:
  applicationConnectors:
    - type: http
      port: 53000
    - type: https
      port: 8443
      keyStorePath: beam.keystore
      keyStorePassword: pa55word
      validateCerts: false
  adminConnectors:
    - type: http
      port: 53001

logging:
  level: INFO
  loggers:
    "com.cobainc0": DEBUG
  appenders:
    - type: file
      currentLogFilename: logs/beam-client.log
      archivedLogFilenamePattern: logs/beam-client.log.%d.gz
appName: Beam Frontend app name
template: Beam template name
defaultName: Beam default name
adminPassword: pa55word
