server:
  applicationConnectors:
    - type: http
      port: 53000
  adminConnectors:
    - type: http
      port: 53001

logging:
  level: INFO
  loggers:
    "uk.gov": DEBUG
  appenders:
    - type: file
      currentLogFilename: logs/beam-client.log
      archivedLogFilenamePattern: logs/beam-client.log.%d.gz
appName: Beam Frontend
