server:
  applicationConnectors:
    - type: http
      port: ${PORT:-53000}
    - type: https
      port: 8443
      keyStorePath: beam.keystore
      keyStorePassword: pa55word
      validateCerts: false
  adminConnectors:
    - type: http
      port: 53001

logging:
  level: NONE
  loggers:
    com.cobainc0: DEBUG
  appenders:
    - type: console
    - type: file
      currentLogFilename: logs/beam-client.log
      archivedLogFilenamePattern: logs/beam-client.log.%d.gz
appName: Beam
template: Beam template name
defaultName: Beam default name
adminPassword: pa55word
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  url: jdbc:mysql://localhost:3306/beam
  password: pa55word
  validationQuery: "/* MyService Health Check */ SELECT 1"

